### ISSUE TITLE
env Bug

### ISSUE THREAD

**Issue by alechstong** [toxsickcoder/node-typescript-starter#10]
Hi,

Great code, man. I've cloned and run you code, and found a little bug.

in package.json, you are setting env.development, for example:

```
  "scripts": {
    "start": "webpack --progress --env.development --env.nodemon",
```

but in webpack.config.js, you are checking env.mode, like

```
      new webpack.DefinePlugin({
        VERSION: JSON.stringify(packageJson.version),
        DEVELOP: env.mode === 'development',
      }),
```

One of these two file need to be changed. (either `--env.mode='development'`, or `DEVELOP: !!env.development`).

**Comment by toxsickcoder** [comment]
Hey, you're absolutely right! Will fix it immediately!
